import Link from "next/link";
import { AuthGate } from "../components/auth-gate";

const activities = [
  ["✦", "Profile workspace", "Import a resume and verify extracted facts", "Start"],
  ["↗", "Application tracker", "Keep next steps and follow-ups visible", "Active"],
  ["▱", "Answer memory", "Save edited answers for reuse", "Next"],
];

export default function Dashboard() { return <AuthGate><DashboardContent /></AuthGate>; }

function DashboardContent() {
  return <div className="dashboard"><aside className="sidebar"><div className="logo"><span className="logo-mark">✦</span>ApplyPilot</div><nav className="nav"><Link className="active" href="/">Overview</Link><Link href="/profile">My profile & resume</Link><Link href="/profile">Resume studio</Link><Link href="/tracker">Job tracker</Link><Link href="/answer-library">Answer library</Link></nav><div className="sidebar-bottom"><strong>Extension status</strong><br />Install the unpacked extension to start filling any page.</div></aside><main className="main"><div className="topbar"><div><div className="eyebrow">Your workspace</div><h1>Good evening, Alex</h1></div><div className="avatar">AA</div></div><section className="hero"><div><div className="eyebrow">One profile. Every application.</div><h2>Apply with your best answer.</h2><p>ApplyPilot detects the question, finds the right context,<br />and gives you a confident answer — even when autofill cannot.</p><div className="hero-actions"><Link href="/profile" className="hero-button">Build profile</Link><Link href="/tracker" className="hero-link">Open tracker →</Link></div></div><div className="hero-graphic"><div className="orbit" /></div></section><div className="grid"><section className="card"><h3>Profile completeness</h3><div className="metric">72%</div><div className="metric-label">Enough to start applying</div><div className="progress"><span /></div><div className="small-note">Import a resume to reach 90%</div></section><section className="card"><h3>Opportunities tracked</h3><div className="metric">3</div><div className="metric-label">Across your application board</div><div className="small-note" style={{ marginTop: 20 }}>Never lose the next step.</div></section><section className="card"><h3>Current mode</h3><div className="metric" style={{ fontSize: 22 }}>Safe first</div><div className="metric-label">Known fields can be suggested</div><div className="small-note" style={{ marginTop: 20 }}>Sensitive questions always need review.</div></section></div><section className="card activity"><div className="section-head"><h3>Workspace activity</h3><Link className="text-link" href="/tracker">View tracker</Link></div>{activities.map(([icon, title, detail, status]) => <div className="activity-row" key={title}><div className="activity-icon">{icon}</div><div><strong>{title}</strong><span>{detail}</span></div><div className="pill">{status}</div></div>)}</section><section className="card" style={{ marginTop: 18 }}><div className="section-head"><h3>Profile snapshot</h3><Link className="text-link" href="/profile">Edit profile</Link></div><div className="profile-list"><div className="profile-item"><span>Name</span><strong>Alex Applicant</strong></div><div className="profile-item"><span>Focus</span><strong>Full-stack Engineer</strong></div><div className="profile-item"><span>Core skills</span><strong>TypeScript · React · Python</strong></div></div></section></main></div>;
}
