import Link from "next/link";
import "./landing.css";

const features = [
  { icon: "✦", title: "Verified profile", text: "Start with your resume, enrich it with projects and GitHub, then review every fact before it becomes reusable context." },
  { icon: "↗", title: "Grounded answers", text: "Known facts and your reviewed answer memory come first. AI only drafts when a question genuinely needs it." },
  { icon: "⌁", title: "Browser assistant", text: "Detect fields, suggest answers, fill what is safe, and keep a copy fallback for the forms that fight back." },
  { icon: "▣", title: "Side Panel fallback", text: "Scan a page, inspect fields, attach a resume, or open your full profile when an in-page widget cannot be controlled." },
  { icon: "◌", title: "Answer memory", text: "Save the answers you have already shaped in your own voice so the next application starts further ahead." },
  { icon: "▤", title: "Application tracker", text: "Save opportunities from the extension and keep stages, notes, interviews, offers, and next steps in one view." },
];

const agents = ["Page", "Profile", "Question", "Memory", "Answer", "Autofill", "Resume", "Validation", "Review", "Learning"];

function CheckIcon() {
  return <span className="check-icon" aria-hidden="true">✓</span>;
}

function ProductPreview() {
  return <div className="product-preview" aria-label="ApplyPilot dashboard and browser extension preview">
    <div className="preview-glow" />
    <div className="browser-window dashboard-window">
      <div className="window-bar"><span /><span /><span /><small>app.applypilot.dev / dashboard</small></div>
      <div className="dashboard-preview-body">
        <aside><div className="mini-brand"><img src="/applypilot-icon.svg" alt="" /> <b>ApplyPilot</b></div><div className="mini-nav active">Overview</div><div className="mini-nav">My profile & resume</div><div className="mini-nav">Job tracker</div><div className="mini-nav">Answer library</div><div className="mini-sidebar-note"><b>Browser extension</b><br />Synced and ready</div></aside>
        <div className="mini-main"><div className="mini-top"><div><label>Your workspace</label><h3>Good morning, Priya</h3></div><i>PS</i></div><div className="mini-hero"><div><label>One profile. Every application.</label><h4>Your profile is ready to apply.</h4><p>Facts first. AI when you need it.</p><button>Open tracker →</button></div><div className="mini-ring"><strong>92%</strong><span>ready</span></div></div><div className="mini-stats"><div><b>92%</b><span>Profile complete</span><em /></div><div><b>12</b><span>Tracked jobs</span><small>3 interviews</small></div><div><b>34</b><span>Answer memories</span><small>Reusable</small></div></div><div className="mini-checklist"><div><CheckIcon /><span><b>Import a resume</b><small>1 resume on file</small></span><strong>Done</strong></div><div><CheckIcon /><span><b>Build your answer library</b><small>34 reusable answers saved</small></span><strong>Done</strong></div></div></div>
      </div>
    </div>
    <div className="browser-window extension-window">
      <div className="extension-head"><img src="/applypilot-icon.svg" alt="" /><div><b>ApplyPilot</b><small>Page assistant</small></div><span>SYNCED</span></div>
      <div className="extension-page"><label>Current page</label><b>Senior Product Designer · Linear</b></div>
      <div className="extension-actions"><span>Scan page</span><span>Fill all</span><span>Attach resume</span><span>Save job</span></div>
      <div className="extension-tabs"><b>Assistant</b><span>My data</span><span>Fields</span><span>Tracker</span></div>
      <label className="extension-question">Question or field prompt</label><div className="extension-textarea">Why are you interested in this role?</div>
      <button className="extension-generate">Generate answer</button>
      <div className="suggestion-card"><div><b>Suggested answer</b><span>MEMORY</span></div><p>I’m excited by the chance to make complex tools feel clear and useful...</p><div><button>Copy</button><button>Insert</button><button>Save</button></div></div>
    </div>
    <div className="preview-badge badge-profile"><span>●</span> Profile match · 92%</div>
    <div className="preview-badge badge-safe"><CheckIcon /> Review before insert</div>
  </div>;
}

export default function LandingPage() {
  return <main className="landing-page">
    <header className="landing-nav"><div className="container nav-inner"><Link href="/" className="brand-lockup"><img src="/applypilot-icon.svg" alt="" /><span>ApplyPilot</span></Link><nav className="desktop-nav"><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#trust">Trust</a><a href="#open-source">Open source</a></nav><div className="nav-actions"><Link href="/login?next=/onboarding" className="nav-signin">Sign in</Link><Link href="/login?next=/onboarding" className="button button-small">Build your profile <span>↗</span></Link></div></div></header>

    <section className="hero-section"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="container hero-grid"><div className="hero-copy"><h1>Apply with your experience.<br /><em>Not AI’s imagination.</em></h1><p className="hero-lede">ApplyPilot builds a verified profile from your resume and helps you answer application questions across the web — with every draft under your control.</p><div className="hero-actions"><Link href="/login?next=/onboarding" className="button button-primary">Build your profile <span>↗</span></Link><a href="#how-it-works" className="button button-ghost">See how it works <span>↓</span></a></div><div className="hero-proof"><span><CheckIcon /> Open source</span><span><CheckIcon /> Review before insert</span><span><CheckIcon /> Never submits for you</span></div></div><ProductPreview /></div><div className="container hero-bottom"><span>Built for the parts of job hunting that repeat</span><div><b>Resume</b><i>×</i><b>Profile</b><i>×</i><b>Browser</b><i>×</i><b>Tracker</b></div></div></section>

    <section className="trust-strip"><div className="container trust-strip-inner"><div><span className="trust-mark">✦</span><p><b>Known facts first.</b> AI second.</p></div><div><span className="trust-mark green">✓</span><p><b>Missing beats invented.</b> Always.</p></div><div><span className="trust-mark orange">◒</span><p><b>You stay in control.</b> Every time.</p></div></div></section>

    <section id="product" className="section section-product"><div className="container"><div className="section-intro centered"><div className="eyebrow">A calmer way to apply</div><h2>One source of truth.<br /><span>Everywhere you apply.</span></h2><p>From the first resume import to the final follow-up, ApplyPilot keeps your real experience close and the repetitive work light.</p></div><div className="feature-grid">{features.map((feature) => <article className="feature-card" key={feature.title}><div className="feature-icon">{feature.icon}</div><h3>{feature.title}</h3><p>{feature.text}</p><a href="#how-it-works">Learn more <span>→</span></a></article>)}</div></div></section>

    <section id="how-it-works" className="section workflow-section"><div className="container"><div className="section-intro"><div className="eyebrow">From resume to ready</div><h2>Build once.<br /><span>Move faster every time.</span></h2><p>ApplyPilot turns your application process into a simple loop: capture the truth, find the right context, review the draft, and keep moving.</p></div><div className="workflow-grid"><div className="workflow-steps"><article className="workflow-step active"><div className="step-number">01</div><div><h3>Import your story</h3><p>Start with a resume. Add GitHub, projects, links, voice notes, and the details only you know.</p><span className="step-tag">Resume-first</span></div></article><article className="workflow-step"><div className="step-number">02</div><div><h3>Verify the signal</h3><p>Review what was extracted, see where it came from, and fill the gaps before it becomes profile memory.</p><span className="step-tag">Source-aware</span></div></article><article className="workflow-step"><div className="step-number">03</div><div><h3>Answer in context</h3><p>The extension detects the question and checks your profile and saved answers before it asks AI.</p><span className="step-tag">Memory-first</span></div></article><article className="workflow-step"><div className="step-number">04</div><div><h3>Review, then move on</h3><p>Copy, insert, edit, save the job, and keep the decision yours. Nothing submits itself.</p><span className="step-tag">Human-approved</span></div></article></div><div className="flow-visual"><div className="flow-card flow-resume"><span className="flow-card-icon">▤</span><div><b>Your resume</b><small>12 roles · 34 skills</small></div><span className="flow-check">✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-profile"><span className="flow-card-icon">✦</span><div><b>Verified profile</b><small>92% complete</small></div><span className="flow-check">✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-answer"><span className="flow-card-icon">⌁</span><div><b>Reviewed answer</b><small>Source: memory</small></div><span className="flow-check">✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-tracker"><span className="flow-card-icon">▤</span><div><b>Next opportunity</b><small>Interview · Friday</small></div><span className="flow-check">→</span></div><div className="flow-orbit orbit-small" /><div className="flow-orbit orbit-large" /></div></div></div></section>

    <section className="section agents-section"><div className="container agents-layout"><div className="agents-copy"><div className="eyebrow">Behind the assist</div><h2>Specialists that work<br /><span>as one careful copilot.</span></h2><p>One orchestrator coordinates ten focused agents. Each handles a small part of the journey, and every AI-generated suggestion still passes through a review boundary.</p><div className="agent-stat"><strong>10</strong><span>specialist agents<br />+ 1 orchestrator</span></div><Link href="/login?next=/onboarding" className="text-link">Build your verified profile <span>↗</span></Link></div><div className="agent-map"><div className="agent-map-core"><img src="/applypilot-icon.svg" alt="" /><b>Application<br />orchestrator</b><small>coordinates the flow</small></div>{agents.map((agent, index) => <div className={`agent-node node-${index + 1}`} key={agent}><span>{String(index + 1).padStart(2, "0")}</span>{agent}</div>)}<div className="agent-ring ring-a" /><div className="agent-ring ring-b" /><div className="agent-pulse" /></div></div></section>

    <section id="trust" className="section trust-section"><div className="container trust-layout"><div className="trust-copy"><div className="eyebrow">Automation with boundaries</div><h2>Helpful should never<br /><span>mean hands-off.</span></h2><p>Job applications are personal. ApplyPilot is designed to reduce repetition without pretending that a model knows you better than you do.</p><Link href="/login?next=/onboarding" className="button button-primary">Start with your resume <span>↗</span></Link></div><div className="trust-list"><div><CheckIcon /><div><b>Missing facts stay missing</b><p>No plausible filler for experience you do not have.</p></div></div><div><CheckIcon /><div><b>Page content is untrusted</b><p>Application text cannot override your profile or the assistant’s rules.</p></div></div><div><CheckIcon /><div><b>Sensitive fields stay review-first</b><p>Work authorization, salary, consent, and submission remain yours.</p></div></div><div><CheckIcon /><div><b>Nothing submits automatically</b><p>ApplyPilot prepares. You review and confirm.</p></div></div></div></div></section>

    <section id="open-source" className="section open-source-section"><div className="container open-source-card"><div className="open-source-mark"><img src="/applypilot-icon.svg" alt="" /></div><div><div className="eyebrow">Open source, by design</div><h2>Your application data deserves<br /><span>inspectable boundaries.</span></h2><p>See how profile data, AI prompts, extension permissions, and database policies fit together. Contribute improvements or run the stack yourself.</p><div className="open-source-actions"><a className="button button-dark" href="https://github.com/rhrits/apply-pilot-agent" target="_blank" rel="noreferrer">Explore on GitHub <span>↗</span></a><a className="text-link light" href="https://github.com/rhrits/apply-pilot-agent/blob/main/SECURITY.md" target="_blank" rel="noreferrer">Read the security model <span>→</span></a></div></div></div></section>

    <footer className="landing-footer"><div className="container footer-inner"><div><Link href="/" className="brand-lockup"><img src="/applypilot-icon.svg" alt="" /><span>ApplyPilot</span></Link><p>The job-application copilot that never invents your experience.</p></div><div className="footer-links"><div><b>Product</b><a href="#product">Features</a><a href="#how-it-works">How it works</a><Link href="/login?next=/onboarding">Get started</Link></div><div><b>Project</b><a href="#open-source">Open source</a><a href="https://github.com/rhrits/apply-pilot-agent/blob/main/SECURITY.md" target="_blank" rel="noreferrer">Security</a><a href="https://github.com/rhrits/apply-pilot-agent" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></div><div className="container footer-bottom"><span>© 2026 ApplyPilot</span><span>Built for accurate applications.</span></div></footer>
  </main>;
}
