import Link from "next/link";
import { ScrollFoxReveal } from "../components/scroll-fox-reveal";
import "./landing.css";
import "./landing-doodle.css";
import "./landing-surfaces.css";

const features = [
  { title: "Verified profile", text: "Start with your resume and project links, then review every fact before it becomes reusable context." },
  { title: "Grounded answers", text: "Your facts and saved answer memory come first. AI only drafts when a question genuinely needs it." },
  { title: "Browser assistant", text: "Detect fields, suggest answers, fill what is safe, and keep a copy fallback when forms fight back." },
  { title: "Side Panel fallback", text: "Scan a page, inspect fields, attach a resume, or open your full profile when a widget cannot be controlled." },
  { title: "Reusable answers", text: "Save answers in your own voice so the next application starts further ahead." },
  { title: "Application tracker", text: "Keep stages, notes, interviews, offers, and next steps in one view." },
];

function CheckIcon() {
  return <span className="check-icon" aria-hidden="true">✓</span>;
}

function MobileFoxExpression() {
  return <svg className="mobile-hero-fox-zoom" viewBox="0 0 512 512" role="img" aria-label="UplyFox playful wink">
    <defs>
      <filter id="mobile-fox-expression-shadow" x="-12%" y="-12%" width="124%" height="124%"><feDropShadow dx="0" dy="10" stdDeviation="11" floodColor="#2b1022" floodOpacity=".24" /></filter>
    </defs>
    <g filter="url(#mobile-fox-expression-shadow)">
      <path d="M64 164 120 64l112 78c16-4 32-6 48-6s32 2 48 6L440 64l8 136c0 122-83 205-168 248C195 405 112 322 112 200Z" fill="#fffdfb" />
      <path d="m64 164 112 48-56 34Z" fill="#ead7d2" />
      <path d="m448 164-112 48 56 34Z" fill="#e7d9e6" />
      <path d="M144 246 224 214l32 36-56 54-56-15Z" fill="#2b1022" />
      <path d="M368 246 288 214l-32 36 32 54 56-15Z" fill="#2b1022" />
      <g className="fox-expression-eye"><rect x="197" y="250" width="18" height="18" rx="4" fill="#fffdfb" /><rect x="203" y="254" width="7" height="10" rx="2" fill="#2b1022" /></g>
      <path className="fox-expression-lid" d="M196 260 215 260" fill="none" stroke="#fffdfb" strokeLinecap="round" strokeWidth="7" />
      <rect x="297" y="250" width="18" height="18" rx="4" fill="#fffdfb" />
      <rect x="302" y="254" width="7" height="10" rx="2" fill="#2b1022" />
      <path className="fox-expression-smirk" d="M216 369 254 398 292 360" fill="none" stroke="#2b1022" strokeLinecap="round" strokeLinejoin="round" strokeWidth="12" />
    </g>
  </svg>;
}

function ProductPreview() {
  return <div className="product-preview" aria-label="UplyFox dashboard and browser extension preview">
    <div className="preview-glow" />
    <div className="browser-window dashboard-window">
      <div className="window-bar"><span /><span /><span /><small>app.uplyfox.com / dashboard</small></div>
      <div className="dashboard-preview-body">
        <aside><div className="mini-brand"><img src="/uplyfox-pixel-crimson-logo.svg" alt="" /> <b>UplyFox</b></div><div className="mini-nav active">Overview</div><div className="mini-nav">My profile</div><div className="mini-nav">Job tracker <span style={{fontSize: 6, padding: '1px 4px', borderRadius: 4, background: 'rgba(255,255,255,0.15)'}}>14</span></div><div className="mini-nav">Answer library <span style={{fontSize: 6, padding: '1px 4px', borderRadius: 4, background: 'rgba(255,255,255,0.15)'}}>34</span></div><div className="mini-sidebar-note"><b>Extension synced</b><br />Auto-detects jobs & answers</div></aside>
        <div className="mini-main"><div className="mini-top"><div><label>Your workspace</label><h3>Good morning, Priya</h3></div><i>PS</i></div><div className="mini-hero"><div><label>One profile. Every application.</label><h4>Your profile is ready to apply.</h4><p>Verified from resume: 8 roles · 32 skills · 6 projects.</p><button>Open tracker →</button></div><div className="mini-ring"><strong>94%</strong><span>ready</span></div></div><div className="mini-stats"><div><b>94%</b><span>Profile complete</span><em /></div><div><b>14</b><span>Tracked jobs</span><small>3 interviews</small></div><div><b>34</b><span>Reusable answers</span><small>Memory active</small></div></div><div className="mini-checklist"><div><CheckIcon /><span><b>Stripe · Staff Engineer</b><small>96% requirement match</small></span><strong style={{background: '#fdf2f5', color: '#8b1e3f', border: '1px solid #f5d7e1'}}>96% Match</strong></div><div><CheckIcon /><span><b>Linear · Senior Frontend</b><small>94% requirement match</small></span><strong style={{background: '#f4f2ff', color: '#5546d9', border: '1px solid #ded9fa'}}>94% Match</strong></div></div></div>
      </div>
    </div>
    <div className="browser-window extension-window">
      <div className="extension-head"><img className="mascot-icon" src="/uplyfox-pixel-crimson-animated.svg" alt="" /><div><b>UplyFox</b><small>Page assistant</small></div><span>SYNCED</span></div>
      <div className="extension-page" style={{background: '#fdf2f5', borderColor: '#f5d7e1'}}><label style={{color: '#8b1e3f'}}>Greenhouse Detected</label><b style={{color: '#1f2040'}}>Staff Frontend Engineer · Linear</b></div>
      <div className="extension-actions"><span>Scan page</span><span>Fill all</span><span>Attach</span><span>Save job</span></div>
      <div className="extension-tabs"><b>Assistant</b><span>My data</span><span>Fields</span><span>Tracker</span></div>
      <label className="extension-question">Question detected on page</label><div className="extension-textarea">Why do you want to work at Linear?</div>
      <div className="suggestion-card" style={{border: '1px solid #ded9fa', background: '#fdfbff'}}><div><b style={{color: '#5546d9'}}>✦ UplyFox suggests</b><span style={{background: '#f4f2ff', color: '#5546d9'}}>MEMORY · 94%</span></div><p>I’m drawn to Linear’s focus on craft, speed, and making complex work feel effortless...</p><div><button style={{background: '#5546d9', color: '#fff'}}>Insert</button><button>Copy</button><button>Save</button></div></div>
    </div>
    <img className="preview-fox-corner" src="/uplyfox-wink-animated.svg" alt="UplyFox" />
    <div className="preview-badge badge-profile"><span>●</span> Match radar · 94%</div>
    <div className="preview-badge badge-safe"><CheckIcon /> Grounded in facts</div>
  </div>;
}

function ProductSurfaces() {
  return <section className="product-surfaces"><div className="section-intro centered"><div className="eyebrow">The product, not a promise</div><h2>See the moments that<br /><span>make applying lighter.</span></h2><p>These are the real UplyFox workflows: inspect the form, prepare safely, track the work, and keep the final decision yours.</p></div><div className="surface-grid">
    <article className="surface-card suggestion-surface"><div className="surface-card-head"><div><span className="surface-kicker">Browser extension · Phase A</span><h3>Inspect before you fill</h3></div><span className="surface-status live"><i /> Read-only</span></div><div className="suggestion-browser"><div className="fake-browser-bar"><span /><span /><span /><small>careers.linear.app / application</small></div><div className="fake-form"><span className="fake-form-label">Application plan · 2 frames inspected</span><div className="fake-input selected">Why do you want to work at Linear?</div><div className="auto-popup"><div className="auto-popup-head"><img src="/uplyfox-pixel-crimson-logo.svg" alt="" /><div><b>UplyFox form plan</b><small>Question, source, confidence</small></div><span>94%</span></div><p>Profile answer found from verified experience. Work authorization stays blocked for manual review.</p><div className="auto-popup-actions"><button>Unknown 2</button><button className="insert">7 ready</button><button className="dismiss">✓</button></div></div><span className="fake-form-label second">Next action</span><div className="fake-input muted">Continue · safe step detected · no submit</div></div></div><div className="surface-caption"><span className="caption-dot purple" /> Scans frames, ARIA fields, options, blockers <span>·</span> No page writes</div></article>

    <article className="surface-card autofill-surface"><div className="surface-card-head"><div><span className="surface-kicker">Workspace dashboard · Live</span><h3>See what to do next</h3></div><span className="surface-status ready"><i /> Insights</span></div><div className="autofill-panel"><div className="autofill-top"><span>Application command center</span><b>14 tracked <strong>↗</strong></b></div><div className="autofill-fields"><div className="autofill-field"><span><small>Do this next</small><b>Review 3 extracted fields</b></span><em>Profile</em><strong>→</strong></div><div className="autofill-field"><span><small>Last 30 days</small><b>8 applications sent</b></span><em>Velocity</em><strong>✓</strong></div><div className="autofill-field"><span><small>Gone quiet</small><b>2 applications · 14+ days</b></span><em>Follow-up</em><strong>!</strong></div><div className="autofill-field"><span><small>Application funnel</small><b>14 saved · 8 applied · 3 interviews</b></span><em>Tracker</em><strong>↗</strong></div><div className="autofill-field review"><span><small>Live role match</small><b>Linear · 94% profile match</b></span><em>Match</em><strong>★</strong></div></div><div className="autofill-footer"><span><i /> Updated from profile + tracker</span><button>Open dashboard</button></div></div><div className="surface-caption"><span className="caption-dot wine" /> Velocity, stale alerts, funnel, next actions <span>·</span> One workspace</div></article>

    <article className="surface-card resume-surface"><div className="surface-card-head"><div><span className="surface-kicker">Profile &amp; sources · Upload first</span><h3>Save the original resume</h3></div><span className="surface-status ready"><i /> Stored</span></div><div className="resume-panel"><div className="resume-file"><div className="pdf-icon">PDF</div><div><b>priya-sharma-resume.pdf</b><small>Stored securely · 2.4 MB · extension ready</small></div><span className="file-check">✓</span></div><div className="extract-progress"><div><span>Original file preview</span><b>Saved</b></div><i><em style={{width: '100%'}} /></i></div><div className="extract-results"><div><strong>1</strong><span>stored file</span></div><div><strong>0</strong><span>profile changes</span></div><div><strong>PDF</strong><span>ready to attach</span></div></div><div className="source-review"><div><span className="source-badge resume">STEP 1</span><b>Upload and save first</b><small>Extraction runs only when you click Extract saved resume</small></div><button>Preview</button></div></div><div className="surface-caption"><span className="caption-dot orange" /> Exact PDF is preserved <span>·</span> You choose when to extract</div></article>

    <article className="surface-card profile-surface"><div className="surface-card-head"><div><span className="surface-kicker">Review gate · Phase D</span><h3>Approve the exact draft</h3></div><span className="surface-status ready"><i /> Human review</span></div><div className="profile-panel"><div className="profile-panel-head"><div className="profile-avatar">✓</div><div><b>Pre-submit draft</b><span>Staff Frontend Engineer · Linear</span></div><button>94% match</button></div><div className="profile-meter"><div><span>Fields ready to review</span><b>18 / 20</b></div><i><em style={{width: '90%'}} /></i></div><div className="profile-facts"><div><span>Source</span><b><strong>✓</strong> Profile + memory</b></div><div><span>Safety</span><b>2 sensitive fields blocked</b></div><div><span>Evidence</span><b>2 frames · hash-bound</b></div></div><div className="profile-note"><span>✦</span><p><b>Nothing submits unseen.</b><br />Review answers, approve this exact snapshot, then decide.</p><button>Approve draft</button></div></div><div className="surface-caption"><span className="caption-dot purple" /> Redacted draft + one-time approval <span>·</span> Final say stays yours</div></article>
  </div></section>;
}

export default function LandingPage() {
  return <main className="landing-page">
    <header className="landing-nav"><div className="container nav-inner"><Link href="/" className="brand-lockup"><img src="/uplyfox-pixel-crimson-animated-logo.svg" alt="" /><span>Uply<strong style={{color: '#8b1e3f'}}>Fox</strong></span></Link><nav className="desktop-nav"><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#trust">Trust</a></nav><div className="nav-actions"><Link href="/login?next=/access" className="nav-signin">Sign in</Link><Link href="/login?next=/access" className="button button-small" style={{background: '#5546d9'}}>Build your profile</Link></div></div></header>

    <section className="hero-section"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="container hero-grid"><div className="hero-copy"><div className="mobile-hero-fox-stage"><img className="mobile-hero-fox" src="/uplyfox-wink-animated.svg" alt="UplyFox" /><MobileFoxExpression /></div><h1>Job Apply AI Agent.<br /><span><em className="hero-wine-word">Apply</em> <em>Fast</em> with Tracking.</span></h1><p className="hero-lede">Build one verified profile from your resume, education, skills, projects, and saved answers. UplyFox uses the facts you provide to match opportunities, suggest grounded answers, and autofill repetitive forms.</p><div className="hero-actions"><Link href="/login?next=/access" className="button button-primary" style={{background: '#5546d9', boxShadow: '0 8px 24px rgba(85,70,217,0.3)'}}>Build your profile</Link><a href="#how-it-works" className="button button-ghost">See how it works</a></div><div className="hero-proof"><span><CheckIcon /> Review before insert</span><span><CheckIcon /> Never auto-submits</span></div><div className="hero-agent-callout"><img src="/uplyfox-pixel-crimson-animated.svg" alt="" /><span><b>Grounded in your information</b><small>Tells you when your profile does not have the answer</small></span></div></div><ProductPreview /></div><div className="container hero-bottom"><span>Resume to ready application</span><div><b>Profile</b><b>Answers</b><b>Autofill</b><b>Tracker</b></div></div></section>

    <section className="trust-strip"><div className="container trust-strip-inner"><div><p><b>Known facts first.</b> AI second.</p></div><div><p><b>Missing beats invented.</b> Always.</p></div><div><p><b>You stay in control.</b> Every time.</p></div></div></section>

    <section id="product" className="section section-product"><div className="container"><div className="section-intro centered"><div className="eyebrow">Everything you need to apply faster</div><h2>One verified profile.<br /><span>Faster applications.</span></h2><p>Keep your real experience, reusable answers, resume, and application history in one place. Use them wherever you apply.</p></div><div className="feature-grid">{features.map((feature) => <article className="feature-card" key={feature.title}><h3>{feature.title}</h3><p>{feature.text}</p><a href="#how-it-works">Learn more</a></article>)}</div><ProductSurfaces /></div></section>

    <section id="how-it-works" className="section workflow-section"><div className="container"><div className="section-intro"><div className="eyebrow">From resume to ready</div><h2>Build once.<br /><span className="workflow-gradient-title">Move faster every time.</span></h2><p>Capture the truth, find the right context, review the draft, keep moving.</p></div><div className="workflow-grid"><div className="workflow-steps"><article className="workflow-step active"><div className="step-number">01</div><div><h3>Import your story</h3><p>Start with a resume. Add projects, portfolio links, voice notes, and the details only you know.</p><span className="step-tag">Resume-first</span></div></article><article className="workflow-step"><div className="step-number">02</div><div><h3>Verify the signal</h3><p>Review what was extracted, see where it came from, and fill the gaps before it becomes profile memory.</p><span className="step-tag">Source-aware</span></div></article><article className="workflow-step"><div className="step-number">03</div><div><h3>Answer in context</h3><p>The extension detects the question and checks your profile and saved answers before it asks AI.</p><span className="step-tag">Memory-first</span></div></article><article className="workflow-step"><div className="step-number">04</div><div><h3>Review, then move on</h3><p>Copy, insert, edit, save the job, and keep the decision yours. Nothing submits itself.</p><span className="step-tag">Human-approved</span></div></article></div><div className="flow-visual"><div className="flow-card flow-resume"><span className="flow-card-icon">▤</span><div><b>Your resume</b><small>12 roles · 34 skills</small></div><span className="flow-check" style={{color: '#8b1e3f'}}>✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-profile"><span className="flow-card-icon">✦</span><div><b>Verified profile</b><small>92% complete</small></div><span className="flow-check">✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-answer"><span className="flow-card-icon">⌁</span><div><b>Reviewed answer</b><small>Source: memory</small></div><span className="flow-check">✓</span></div><div className="flow-line"><i /><i /><i /></div><div className="flow-card flow-tracker"><span className="flow-card-icon">▤</span><div><b>Next opportunity</b><small>Interview · Friday</small></div><span className="flow-check">→</span></div><div className="flow-orbit orbit-small" /><div className="flow-orbit orbit-large" /></div></div></div></section>

    <section id="trust" className="section trust-section"><div className="container trust-layout"><div className="trust-copy"><div className="eyebrow">Automation with boundaries</div><h2>Helpful should never<br /><span>mean hands-off.</span></h2><p>Job applications are personal. UplyFox reduces repetition without pretending a model knows you better than you do.</p><Link href="/login?next=/access" className="button button-primary">Start with your resume</Link></div><div className="trust-list"><div><CheckIcon /><div><b>Missing facts stay missing</b><p>No plausible filler for experience you do not have.</p></div></div><div><CheckIcon /><div><b>Page content is untrusted</b><p>Application text cannot override your profile or the assistant’s rules.</p></div></div><div><CheckIcon /><div><b>Sensitive fields stay review-first</b><p>Work authorization, salary, consent, and submission remain yours.</p></div></div><div><CheckIcon /><div><b>Nothing submits automatically</b><p>UplyFox prepares. You review and confirm.</p></div></div></div></div></section>

    <ScrollFoxReveal />
    <footer className="landing-footer"><div className="container footer-inner"><div><Link href="/" className="brand-lockup"><img src="/uplyfox-pixel-crimson-animated-logo.svg" alt="" /><span>Uply<strong style={{color: '#8b1e3f'}}>Fox</strong></span></Link><p>The job application assistant that never invents your experience.</p></div><div className="footer-links"><div><b>Product</b><a href="#product">Features</a><a href="#how-it-works">How it works</a><a href="#trust">Trust</a><Link href="/login?next=/access">Get started</Link></div></div></div><div className="container footer-bottom"><span>© 2026 UplyFox</span><span>Built by Hritik.</span></div></footer>
  </main>;
}
